create type public.customer_source as enum ('EXTERNAL_SALES', 'DIRECT_WCAT');
create type public.customer_status as enum ('PROSPECT', 'ACTIVE_CUSTOMER', 'INACTIVE');
create type public.spec_status as enum ('DRAFT', 'APPROVED', 'INACTIVE');
create type public.incoterm as enum ('FOB', 'CIF', 'CNF');
create type public.po_currency as enum ('USD', 'EUR', 'THB');
create type public.commercial_decision as enum ('AUTO_PASS', 'PENDING_APPROVAL', 'NO_ACTIVE_STANDARD', 'APPROVED_SPECIAL', 'REJECTED');
create type public.special_price_status as enum ('PENDING', 'APPROVED', 'REJECTED', 'USED_IN_PO', 'EXPIRED');

create table public.customers (
 id uuid primary key default gen_random_uuid(), name text not null, source public.customer_source not null,
 owner_profile_id uuid references public.user_profiles(id), status public.customer_status not null,
 first_po_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 check ((source = 'EXTERNAL_SALES' and owner_profile_id is not null and status = 'ACTIVE_CUSTOMER') or source = 'DIRECT_WCAT')
);
create table public.customer_ownership_history (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, old_owner_profile_id uuid references public.user_profiles(id), new_owner_profile_id uuid references public.user_profiles(id), reason text not null, changed_by uuid not null references public.user_profiles(id), changed_at timestamptz not null default now());
create table public.customer_contacts (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, name text not null, position text, email text, phone text, messaging_handle text, is_active boolean not null default true, remark text, created_at timestamptz not null default now());
create table public.crm_activities (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, activity_date date not null default current_date, topic text not null, channel text not null, note text not null, related_type text not null default 'CUSTOMER', related_reference text, created_by uuid not null default public.current_profile_id(), created_at timestamptz not null default now());
create table public.action_required (id uuid primary key default gen_random_uuid(), activity_id uuid not null references public.crm_activities(id) on delete cascade, action text not null, responsible_profile_id uuid references public.user_profiles(id), due_date date, status text not null default 'OPEN' check (status in ('OPEN','IN_PROGRESS','DONE')), completed_at timestamptz);

create table public.products (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, grade text, description text, hs_code text, shelf_life text, is_active boolean not null default true, remark text, created_at timestamptz not null default now());
create table public.product_specs (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, name text not null, version text not null, status public.spec_status not null default 'DRAFT', effective_date date, parameters jsonb not null default '{}'::jsonb, note text, unique(product_id, version));
create table public.shipment_configurations (id uuid primary key default gen_random_uuid(), shipment_mode text not null, container_type text not null, package text not null, bag_weight_kg numeric, bags_per_container integer, standard_mt_per_container numeric not null, tolerance_percent numeric default 0, is_active boolean not null default true, remark text);
create table public.product_shipment_configurations (product_id uuid references public.products(id) on delete cascade, shipment_configuration_id uuid references public.shipment_configurations(id) on delete cascade, primary key(product_id, shipment_configuration_id));

create table public.standard_fob_prices (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id), product_spec_id uuid not null references public.product_specs(id), fob_usd_mt numeric(14,4) not null check(fob_usd_mt >= 0), effective_date date not null, valid_until date not null, status text not null default 'ACTIVE' check(status in ('ACTIVE','EXPIRED','CANCELLED')), set_by uuid references public.user_profiles(id), note text, created_at timestamptz not null default now(), check(valid_until >= effective_date));
create table public.special_price_requests (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id), product_id uuid not null references public.products(id), product_spec_id uuid not null references public.product_specs(id), requested_fob_usd_mt numeric(14,4) not null, approved_fob_usd_mt numeric(14,4), standard_fob_snapshot numeric(14,4), status public.special_price_status not null default 'PENDING', valid_until date, linked_po_id uuid unique, reason text not null, requested_by uuid not null default public.current_profile_id(), approved_by uuid references public.user_profiles(id), approved_at timestamptz, note text);

create table public.purchase_orders (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id), customer_po_number text not null, po_date date not null, product_id uuid not null references public.products(id), product_spec_id uuid not null references public.product_specs(id), product_spec_snapshot jsonb not null default '{}'::jsonb, shipment_configuration_id uuid references public.shipment_configurations(id), contract_quantity_mt numeric(14,4) not null check(contract_quantity_mt > 0), incoterm public.incoterm not null, destination text not null, payment_term text, currency public.po_currency not null, final_selling_price numeric(14,4) not null check(final_selling_price >= 0), commission_usd_mt numeric(14,4) not null default 0, freight_snapshot_usd_mt numeric(14,4), fob_base_snapshot_usd_mt numeric(14,4), fx_rate numeric(18,8), fx_bank_name text, fx_rate_date date, fx_approved_by uuid references public.user_profiles(id), fx_approved_at timestamptz, commercial_decision public.commercial_decision not null default 'PENDING_APPROVAL', commercial_reason text, created_by uuid not null default public.current_profile_id(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(customer_id, customer_po_number), check((incoterm = 'FOB' and freight_snapshot_usd_mt is null) or (incoterm in ('CIF','CNF') and freight_snapshot_usd_mt is not null)), check((currency = 'USD') or fx_rate is not null));
alter table public.customers add constraint customers_first_po_fk foreign key(first_po_id) references public.purchase_orders(id) deferrable initially deferred;

create or replace function public.get_active_standard_fob(p_product_id uuid, p_product_spec_id uuid, p_on_date date default current_date) returns public.standard_fob_prices language sql stable security definer set search_path = public as $$ select p from public.standard_fob_prices p where p.product_id=p_product_id and p.product_spec_id=p_product_spec_id and p.status='ACTIVE' and p.effective_date <= p_on_date and p.valid_until >= p_on_date order by p.effective_date desc limit 1; $$;
create or replace function public.can_access_customer(p_customer_id uuid) returns boolean language sql stable security definer set search_path = public as $$ select public.is_internal_user() or exists(select 1 from public.customers where id=p_customer_id and owner_profile_id=public.current_profile_id()); $$;

alter table public.customers enable row level security; alter table public.customer_contacts enable row level security; alter table public.crm_activities enable row level security; alter table public.action_required enable row level security; alter table public.products enable row level security; alter table public.product_specs enable row level security; alter table public.shipment_configurations enable row level security; alter table public.standard_fob_prices enable row level security; alter table public.special_price_requests enable row level security; alter table public.purchase_orders enable row level security;
create policy "customer access" on public.customers for all to authenticated using(public.can_access_customer(id)) with check(public.is_internal_user() or owner_profile_id=public.current_profile_id());
create policy "contacts access" on public.customer_contacts for all to authenticated using(public.can_access_customer(customer_id)) with check(public.can_access_customer(customer_id));
create policy "crm access" on public.crm_activities for all to authenticated using(public.can_access_customer(customer_id)) with check(public.can_access_customer(customer_id));
create policy "actions access" on public.action_required for all to authenticated using(exists(select 1 from public.crm_activities a where a.id=activity_id and public.can_access_customer(a.customer_id))) with check(exists(select 1 from public.crm_activities a where a.id=activity_id and public.can_access_customer(a.customer_id)));
create policy "master read" on public.products for select to authenticated using(public.is_active_profile()); create policy "master manage" on public.products for all to authenticated using(public.is_internal_user()) with check(public.is_internal_user());
create policy "spec read" on public.product_specs for select to authenticated using(public.is_active_profile()); create policy "spec manage" on public.product_specs for all to authenticated using(public.is_internal_user()) with check(public.is_internal_user());
create policy "config read" on public.shipment_configurations for select to authenticated using(public.is_active_profile()); create policy "config manage" on public.shipment_configurations for all to authenticated using(public.is_internal_user()) with check(public.is_internal_user());
create policy "price read" on public.standard_fob_prices for select to authenticated using(public.is_active_profile()); create policy "price manage" on public.standard_fob_prices for all to authenticated using(public.has_app_role('MANAGEMENT') or public.has_app_role('ADMIN')) with check(public.has_app_role('MANAGEMENT') or public.has_app_role('ADMIN'));
create policy "po access" on public.purchase_orders for all to authenticated using(public.can_access_customer(customer_id)) with check(public.can_access_customer(customer_id));
